name: af_animations
description: Create animations very easily, with high performance on all platforms.
version: 0.3.0
homepage: https://github.com/FernandoDev007
repository: https://github.com/FernandoDev007/af_animations
issue_tracker: https://github.com/FernandoDev007/af_animations/issues

environment:
  sdk: ">=2.19.6 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
